### ISSUE TITLE
注册bug

### ISSUE THREAD

**Issue by mcyydscc** [b1ackc4t/MarsCTF#1]
注册界面，用户名密码什么都不填，直接点注册，可以注册成功

**Comment by mcyydscc** [comment]
还希望可以加一个注册验证码，不然容易被写脚本暴力填充数据库

**Comment by mcyydscc** [comment]
第二个bug是 后台管理界面-用户积分 查看详情无反应
第三个bug是 普通用户可以进入后台页面，查看用户注册情况，积分情况等等

**Comment by b1ackc4t** [comment]
已修复
