### ISSUE TITLE
管理员账号漏洞

### ISSUE THREAD

**Issue by mcyydscc** [b1ackc4t/MarsCTF#2]
首先得到管理员账号，例如管理员账号是admin
然后注册一个账号，给admin前加个空格，就是 admin
然后注册成功后就能进入后台，随意修改东西，虽然角色是ROLE_user，但实际能修改任何东西！

**Comment by mcyydscc** [comment]
我刚才再看了一下，其实也不能算是漏洞，注册这个账号之后，登陆时前面加上空格，是不能登陆的，但是会出现重名风险

**Comment by b1ackc4t** [comment]
感谢关注marsctf安全，重名的垃圾账户无法登录，数据也均为空，不会影响正常用户使用，危害较低先不处理，暂考虑于下一版本再修复。
希望以后能加上图，有助于我判断漏洞影响和复现过程，感谢

**Comment by b1ackc4t** [comment]
已修复

**Comment by mcyydscc** [comment]
> 
![image](https://user-images.githubusercontent.com/90653809/183637265-8576d67a-79a5-4a58-ac38-3a014a981758.png)
![image](https://user-images.githubusercontent.com/90653809/183637308-f7d96325-965f-4ab0-bcde-51702c126f13.png)
![image](https://user-images.githubusercontent.com/90653809/183637519-3f908759-b710-4527-8ef5-675a25fee6de.png)

大佬，进去后会出现报错，题目数量什么的也不会显示，验证码也加载失败

**Comment by mcyydscc** [comment]
这个好像是不是验证的一种限制，只能60s ping一次

**Comment by b1ackc4t** [comment]
新发了V1.2.1，现在应该没问题了 我拿VPS试装了好几次

**Comment by mcyydscc** [comment]
![image](https://user-images.githubusercontent.com/90653809/183652538-9096b462-0fa4-40ac-b46b-698ac8fc88f2.png)
![image](https://user-images.githubusercontent.com/90653809/183652630-2c5d1c04-847c-4771-943c-dbddf2efc6fa.png)
大佬好像还是这样，似乎第一次进去一切正常，然后另开一个浏览器就会出错，第一次进去的那个账号，退出清理缓存，也会报错

**Comment by b1ackc4t** [comment]
f12 network看一下请求的详细报错信息，验证码都显示不出来不应该啊

**Comment by mcyydscc** [comment]
> f12 network看一下请求的详细报错信息，验证码都显示不出来不应该啊

刚才找到原因了，有一个服务没有启动起来，重启了两次好了

**Comment by fwsilent** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/90653809/183637265-8576d67a-79a5-4a58-ac38-3a014a981758.png) ![image](https://user-images.githubusercontent.com/90653809/183637308-f7d96325-965f-4ab0-bcde-51702c126f13.png) ![image](https://user-images.githubusercontent.com/90653809/183637519-3f908759-b710-4527-8ef5-675a25fee6de.png)
> 
> 大佬，进去后会出现报错，题目数量什么的也不会显示，验证码也加载失败

请问你是怎么解决的？我也是会显示这么多的network error

**Comment by mcyydscc** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/90653809/183637265-8576d67a-79a5-4a58-ac38-3a014a981758.png) ![image](https://user-images.githubusercontent.com/90653809/183637308-f7d96325-965f-4ab0-bcde-51702c126f13.png) ![image](https://user-images.githubusercontent.com/90653809/183637519-3f908759-b710-4527-8ef5-675a25fee6de.png)
> > 大佬，进去后会出现报错，题目数量什么的也不会显示，验证码也加载失败
> 
> 请问你是怎么解决的？我也是会显示这么多的network error

盲猜你没有修改/marsctf-docker/nginx/html/config.json的BASE_URL_PROD

**Comment by fwsilent** [comment]
> > > > 
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/90653809/183637265-8576d67a-79a5-4a58-ac38-3a014a981758.png) ![image](https://user-images.githubusercontent.com/90653809/183637308-f7d96325-965f-4ab0-bcde-51702c126f13.png) ![image](https://user-images.githubusercontent.com/90653809/183637519-3f908759-b710-4527-8ef5-675a25fee6de.png)
> > > 大佬，进去后会出现报错，题目数量什么的也不会显示，验证码也加载失败
> > 
> > 
> > 请问你是怎么解决的？我也是会显示这么多的network error
> 
> 盲猜你没有修改/marsctf-docker/nginx/html/config.json的BASE_URL_PROD

这个也改了。但是登陆也有问题，F12查看后，发现login，返回：
{flag: false, msg: "服务器故障 请稍后再试"}
flag: false
msg: "服务器故障 请稍后再试"

我直接用命令 java -jar ./marsctf-server-0.0.1-SNAPSHOT.jar 也报错了。

**Comment by fwsilent** [comment]
> > f12 network看一下请求的详细报错信息，验证码都显示不出来不应该啊
> 
> 刚才找到原因了，有一个服务没有启动起来，重启了两次好了

能够把你可以正常使用的发我一份。感觉jar文件中加了验证码功能，但是前端页面中没有验证码输入，导致后台接收不到验证码参数，从而出错。是不是作者更新了后端，前端忘了更新？

**Comment by b1ackc4t** [comment]
> > > f12 network看一下请求的详细报错信息，验证码都显示不出来不应该啊
> > 
> > 
> > 刚才找到原因了，有一个服务没有启动起来，重启了两次好了
> 
> 能够把你可以正常使用的发我一份。感觉jar文件中加了验证码功能，但是前端页面中没有验证码输入，导致后台接收不到验证码参数，从而出错。是不是作者更新了后端，前端忘了更新？

确实上错了，我最后一次更新老眼昏花只上了jar包了:cry:，现在已经改成了全套压缩包，不好意思

**Comment by fwsilent** [comment]
> > > > f12 network看一下请求的详细报错信息，验证码都显示不出来不应该啊
> > > 
> > > 
> > > 刚才找到原因了，有一个服务没有启动起来，重启了两次好了
> > 
> > 
> > 能够把你可以正常使用的发我一份。感觉jar文件中加了验证码功能，但是前端页面中没有验证码输入，导致后台接收不到验证码参数，从而出错。是不是作者更新了后端，前端忘了更新？
> 
> 确实上错了，我最后一次更新老眼昏花只上了jar包了😢，现在已经改成了全套压缩包，不好意思

大佬，下了新的压缩包，但是用admin/123456登陆的时候还是报错，F12后，发现login的返回结果扔为：
{flag: false, msg: "服务器故障 请稍后再试"}
flag: false
msg: "服务器故障 请稍后再试"

查看后台报错信息，还和之前一样：
![image](https://user-images.githubusercontent.com/32404852/184470393-180ad97c-20c3-4481-bca6-8e02dc65fee5.png)

大佬再帮忙看看是啥问题呢？

**Comment by b1ackc4t** [comment]
> > > > > f12 network看一下请求的详细报错信息，验证码都显示不出来不应该啊
> > > > 
> > > > 
> > > > 刚才找到原因了，有一个服务没有启动起来，重启了两次好了
> > > 
> > > 
> > > 能够把你可以正常使用的发我一份。感觉jar文件中加了验证码功能，但是前端页面中没有验证码输入，导致后台接收不到验证码参数，从而出错。是不是作者更新了后端，前端忘了更新？
> > 
> > 
> > 确实上错了，我最后一次更新老眼昏花只上了jar包了😢，现在已经改成了全套压缩包，不好意思
> 
> 大佬，下了新的压缩包，但是用admin/123456登陆的时候还是报错，F12后，发现login的返回结果扔为： {flag: false, msg: "服务器故障 请稍后再试"} flag: false msg: "服务器故障 请稍后再试"
> 
> 查看后台报错信息，还和之前一样： ![image](https://user-images.githubusercontent.com/32404852/184470393-180ad97c-20c3-4481-bca6-8e02dc65fee5.png)
> 
> 大佬再帮忙看看是啥问题呢？

sudo docker-compose up --build
ctrl f5强制刷新 关闭缓存

**Comment by fwsilent** [comment]
> > > > > > f12 network看一下请求的详细报错信息，验证码都显示不出来不应该啊
> > > > > 
> > > > > 
> > > > > 刚才找到原因了，有一个服务没有启动起来，重启了两次好了
> > > > 
> > > > 
> > > > 能够把你可以正常使用的发我一份。感觉jar文件中加了验证码功能，但是前端页面中没有验证码输入，导致后台接收不到验证码参数，从而出错。是不是作者更新了后端，前端忘了更新？
> > > 
> > > 
> > > 确实上错了，我最后一次更新老眼昏花只上了jar包了😢，现在已经改成了全套压缩包，不好意思
> > 
> > 
> > 大佬，下了新的压缩包，但是用admin/123456登陆的时候还是报错，F12后，发现login的返回结果扔为： {flag: false, msg: "服务器故障 请稍后再试"} flag: false msg: "服务器故障 请稍后再试"
> > 查看后台报错信息，还和之前一样： ![image](https://user-images.githubusercontent.com/32404852/184470393-180ad97c-20c3-4481-bca6-8e02dc65fee5.png)
> > 大佬再帮忙看看是啥问题呢？
> 
> sudo docker-compose up --build ctrl f5强制刷新 关闭缓存

可以正常访问了。感谢。准备好好学习下。有问题再请教。

**Comment by wh1t3zer** [comment]
大佬，想问下配置动态靶机的时候，获取镜像失败是什么问题，第一用这种平台不是很懂

**Comment by b1ackc4t** [comment]
你先看看你直接用docker pull 镜像名 能成功吗，镜像名确定能用吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月26日(星期五) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [b1ackc4t/MarsCTF] 管理员账号漏洞 (Issue #2)





 
大佬，想问下配置动态靶机的时候，获取镜像失败是什么问题，第一用这种平台不是很懂

**Comment by wh1t3zer** [comment]
> 你先看看你直接用docker pull 镜像名 能成功吗，镜像名确定能用吗
> […](#)

就是我导入一些赛题，用docker-compose构建的，能访问环境但是镜像导入说镜像不存在

**Comment by b1ackc4t** [comment]
首先用docker-compose构建的可能是多镜像的题目，多镜像题目本平台不支持，如果你那个题是单镜像的，你检查你输的镜像名是否正确，在dockerhub是否存在




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月26日(星期五) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [b1ackc4t/MarsCTF] 管理员账号漏洞 (Issue #2)





  
你先看看你直接用docker pull 镜像名 能成功吗，镜像名确定能用吗
 …
  
就是我导入一些赛题，用docker-compose构建的，能访问环境但是镜像导入说镜像不存在

**Comment by wh1t3zer** [comment]
> 首先用docker-compose构建的可能是多镜像的题目，多镜像题目本平台不支持，如果你那个题是单镜像的，你检查你输的镜像名是否正确，在dockerhub是否存在
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年8月26日(星期五) 下午5:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [b1ackc4t/MarsCTF] 管理员账号漏洞 (Issue #2) 你先看看你直接用docker pull 镜像名 能成功吗，镜像名确定能用吗 … 就是我导入一些赛题，用docker-compose构建的，能访问环境但是镜像导入说镜像不存在 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

emmm那个我在dockerhub上传镜像之后，那个配置里面docker Registry地址要怎么填，能docker pull

**Comment by mcyydscc** [comment]
> > 首先用docker-compose构建的可能是多镜像的题目，多镜像题目本平台不支持，如果你那个题是单镜像的，你检查你输的镜像名是否正确，在dockerhub是否存在
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年8月26日(星期五) 下午5:54 收件人: _**@**_.**_>; 抄送: _**@**_._**>; "State _**@**_.**_>; 主题: Re: [b1ackc4t/MarsCTF] 管理员账号漏洞 (Issue #2) 你先看看你直接用docker pull 镜像名 能成功吗，镜像名确定能用吗 … 就是我导入一些赛题，用docker-compose构建的，能访问环境但是镜像导入说镜像不存在 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> emmm那个我在dockerhub上传镜像之后，那个配置里面docker Registry地址要怎么填，能docker pull
`.
├── Dockerfile   #生成镜像的脚本
├── files
│   ├── flag.sh  #替换flag.php中的FLAG生成动态flag的文件
│   ├── php.ini  #自定义php.ini
│   └── start.sh #启动Web服务、执行生成动态flag的脚本
└── src
    ├── flag.php #flag位置
    └── index.php#代码审计主页

2 directories, 6 files`

源码配置完成之后，进入Dockerfile目录
执行下方代码构建镜像
`docker build -t 你的昵称/容器昵称 .`
然后将镜像push到dockerhub中
`docker push 你的昵称/容器昵称`

**Comment by wh1t3zer** [comment]
> > > 首先用docker-compose构建的可能是多镜像的题目，多镜像题目本平台不支持，如果你那个题是单镜像的，你检查你输的镜像名是否正确，在dockerhub是否存在
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2022年8月26日(星期五) 下午5:54 收件人: _**@**_.**_>; 抄送: _**@**_._**>; "State _**@**_.**_>; 主题: Re: [b1ackc4t/MarsCTF] 管理员账号漏洞 (Issue #2) 你先看看你直接用docker pull 镜像名 能成功吗，镜像名确定能用吗 … 就是我导入一些赛题，用docker-compose构建的，能访问环境但是镜像导入说镜像不存在 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> > 
> > 
> > emmm那个我在dockerhub上传镜像之后，那个配置里面docker Registry地址要怎么填，能docker pull
> > `.
> > ├── Dockerfile   #生成镜像的脚本
> > ├── files
> > │   ├── flag.sh  #替换flag.php中的FLAG生成动态flag的文件
> > │   ├── php.ini  #自定义php.ini
> > │   └── start.sh #启动Web服务、执行生成动态flag的脚本
> > └── src
> > ├── flag.php #flag位置
> > └── index.php#代码审计主页
> 
> 2 directories, 6 files`
> 
> 源码配置完成之后，进入Dockerfile目录 执行下方代码构建镜像 `docker build -t 你的昵称/容器昵称 .` 然后将镜像push到dockerhub中 `docker push 你的昵称/容器昵称`

好的已经解决了，感谢大佬
