### ISSUE TITLE
登陆或者注册显示服务器故障

### ISSUE THREAD

**Issue by fwsilent** [b1ackc4t/MarsCTF#3]
{flag: false, msg: "服务器故障 请稍后再试"}
flag: false
msg: "服务器故障 请稍后再试"

[root@localhost marsctf-docker]# docker-compose restart
[+] Running 3/3
 ⠿ Container marsctf-docker-db-1     St...                                 4.7s
 ⠿ Container marsctf-docker-main-1   Started                               0.9s
 ⠿ Container marsctf-docker-nginx-1  Started                               0.9s

这个是docker启动的容器

请问是什么问题，我觉得是后端服务没起来，但是我对java不熟，不知道怎么处理，谢谢

**Comment by fwsilent** [comment]
> {flag: false, msg: "服务器故障 请稍后再试"} flag: false msg: "服务器故障 请稍后再试"
> 
> [root@localhost marsctf-docker]# docker-compose restart [+] Running 3/3 ⠿ Container marsctf-docker-db-1 St... 4.7s ⠿ Container marsctf-docker-main-1 Started 0.9s ⠿ Container marsctf-docker-nginx-1 Started 0.9s
> 
> 这个是docker启动的容器
> 
> 请问是什么问题，我觉得是后端服务没起来，但是我对java不熟，不知道怎么处理，谢谢

**Comment by fwsilent** [comment]
大佬，按照你的教程，没有能够完全启动好，后台感觉没有起来。

**Comment by fwsilent** [comment]
大佬，有没有qq等联系方式，可以请教下的。

**Comment by fwsilent** [comment]
登陆的时候，发现报错：
![image](https://user-images.githubusercontent.com/32404852/184401518-e794b2bd-ae28-4d93-8b5c-e8eaacfb240f.png)

**Comment by fwsilent** [comment]
![image](https://user-images.githubusercontent.com/32404852/184406009-47133431-40a7-4435-9c1f-ff164c59c8b9.png)
作者大佬，1.2.1能否上传一个完整的docker版本

**Comment by b1ackc4t** [comment]
确实上错了，我最后一次更新老眼昏花只上了jar包了😢，现在已经改成了全套压缩包，不好意思
